# Generated by Django 5.1.3 on 2024-11-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_department_user_user_position_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.IntegerField(choices=[(1, 'Approve'), (2, 'Disapprove'), (3, 'Not yet approved')], default=3),
        ),
    ]
